spring:
  profiles:
    active: ${ENV_NAME:dev}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,mappings
springdoc:
  swagger-ui:
    path: /swagger-ui.html


